// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBrutePayloadSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBrutePayloadSet'](arg1, arg2, arg3);
}

export function CreateBruteTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBruteTask'](arg1, arg2, arg3);
}

export function CreateDomainBruteTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDomainBruteTask'](arg1, arg2, arg3, arg4);
}

export function CreateHttpRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateHttpRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePortScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePortScanTask'](arg1, arg2, arg3, arg4);
}

export function CreateScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateScanTask'](arg1, arg2, arg3, arg4);
}

export function CreateTarget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTarget'](arg1, arg2, arg3, arg4);
}

export function CreateVulnerability(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateVulnerability'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteHttpRequest(arg1) {
  return window['go']['main']['App']['DeleteHttpRequest'](arg1);
}

export function DeleteScanTask(arg1) {
  return window['go']['main']['App']['DeleteScanTask'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function DeleteVulnerability(arg1) {
  return window['go']['main']['App']['DeleteVulnerability'](arg1);
}

export function GetAllBrutePayloadSets() {
  return window['go']['main']['App']['GetAllBrutePayloadSets']();
}

export function GetAllBruteTasks() {
  return window['go']['main']['App']['GetAllBruteTasks']();
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAllDomainBruteTasks() {
  return window['go']['main']['App']['GetAllDomainBruteTasks']();
}

export function GetAllHttpRequests() {
  return window['go']['main']['App']['GetAllHttpRequests']();
}

export function GetAllPortScanTasks() {
  return window['go']['main']['App']['GetAllPortScanTasks']();
}

export function GetAllScanTasks() {
  return window['go']['main']['App']['GetAllScanTasks']();
}

export function GetAllTargets() {
  return window['go']['main']['App']['GetAllTargets']();
}

export function GetAllVulnerabilities() {
  return window['go']['main']['App']['GetAllVulnerabilities']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetDomainBruteResults(arg1) {
  return window['go']['main']['App']['GetDomainBruteResults'](arg1);
}

export function GetHttpRequestByID(arg1) {
  return window['go']['main']['App']['GetHttpRequestByID'](arg1);
}

export function GetHttpResponseHistory(arg1) {
  return window['go']['main']['App']['GetHttpResponseHistory'](arg1);
}

export function GetNucleiStatus() {
  return window['go']['main']['App']['GetNucleiStatus']();
}

export function GetPortScanResults(arg1) {
  return window['go']['main']['App']['GetPortScanResults'](arg1);
}

export function GetScanProgress(arg1) {
  return window['go']['main']['App']['GetScanProgress'](arg1);
}

export function GetScanTaskByID(arg1) {
  return window['go']['main']['App']['GetScanTaskByID'](arg1);
}

export function GetTargetByID(arg1) {
  return window['go']['main']['App']['GetTargetByID'](arg1);
}

export function GetVulnerabilitiesByTaskID(arg1) {
  return window['go']['main']['App']['GetVulnerabilitiesByTaskID'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function InstallNuclei() {
  return window['go']['main']['App']['InstallNuclei']();
}

export function LogFromFrontend(arg1, arg2) {
  return window['go']['main']['App']['LogFromFrontend'](arg1, arg2);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan(arg1) {
  return window['go']['main']['App']['StopScan'](arg1);
}

export function UpdateHttpRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateHttpRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateScanTaskProgress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScanTaskProgress'](arg1, arg2, arg3, arg4);
}

export function UpdateScanTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateScanTaskStatus'](arg1, arg2);
}

export function UpdateTarget(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTarget'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateVulnerability(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVulnerability'](arg1, arg2, arg3);
}
