// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTemplatesToScenarioGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateBrutePayloadSet(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function CreateBruteTask(arg1:string,arg2:number,arg3:string):Promise<number>;

export function CreateCustomTemplate(arg1:string,arg2:string):Promise<number>;

export function CreateDomainBruteTask(arg1:string,arg2:Array<string>,arg3:number,arg4:number):Promise<number>;

export function CreateHttpRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:string,arg7:Array<string>):Promise<number>;

export function CreatePortScanTask(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<number>;

export function CreateScanTask(arg1:string,arg2:number,arg3:string,arg4:Array<string>):Promise<number>;

export function CreateScenarioGroup(arg1:string,arg2:string):Promise<main.ScenarioGroup>;

export function CreateTarget(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<number>;

export function CreateVulnerability(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number):Promise<number>;

export function DeleteCustomTemplate(arg1:number):Promise<void>;

export function DeleteHttpRequest(arg1:number):Promise<void>;

export function DeleteScanTask(arg1:number):Promise<void>;

export function DeleteScenarioGroup(arg1:string):Promise<void>;

export function DeleteTarget(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DeleteVulnerability(arg1:number):Promise<void>;

export function GetAllBrutePayloadSets():Promise<Array<main.BrutePayloadSet>>;

export function GetAllBruteTasks():Promise<Array<main.BruteTask>>;

export function GetAllConfigs():Promise<Record<string, string>>;

export function GetAllCustomTemplates():Promise<Array<main.CustomTemplate>>;

export function GetAllDomainBruteTasks():Promise<Array<main.DomainBruteTask>>;

export function GetAllHttpRequests():Promise<Array<main.HttpRequest>>;

export function GetAllNucleiTemplates():Promise<Array<main.NucleiTemplate>>;

export function GetAllPortScanTasks():Promise<Array<main.PortScanTask>>;

export function GetAllScanTasks():Promise<Array<main.ScanTask>>;

export function GetAllTargets():Promise<Array<main.Target>>;

export function GetAllVulnerabilities():Promise<Array<main.Vulnerability>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetCustomTemplateByID(arg1:number):Promise<main.CustomTemplate>;

export function GetCustomTemplatesDir():Promise<string>;

export function GetCustomTemplatesStats():Promise<Record<string, any>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDomainBruteResults(arg1:number):Promise<Array<main.DomainBruteResult>>;

export function GetHttpRequestByID(arg1:number):Promise<main.HttpRequest>;

export function GetHttpResponseHistory(arg1:number):Promise<Array<main.HttpResponse>>;

export function GetNucleiStatus():Promise<main.NucleiStatus>;

export function GetNucleiTemplateBySeverity(arg1:string):Promise<Array<main.NucleiTemplate>>;

export function GetNucleiTemplateContent(arg1:string):Promise<string>;

export function GetNucleiTemplatesCategories():Promise<Record<string, any>>;

export function GetNucleiTemplatesDir():Promise<string>;

export function GetNucleiTemplatesPaginated(arg1:number,arg2:number):Promise<main.PaginatedTemplatesResult>;

export function GetNucleiTemplatesPaginatedV2(arg1:main.TemplateFilter):Promise<main.PaginatedTemplatesResult>;

export function GetPortScanResults(arg1:number):Promise<Array<main.PortScanResult>>;

export function GetScanProgress(arg1:number):Promise<main.ScanProgress>;

export function GetScanTaskByID(arg1:number):Promise<main.ScanTask>;

export function GetScenarioGroupByID(arg1:string):Promise<main.ScenarioGroup>;

export function GetScenarioGroupTemplates(arg1:string):Promise<Array<main.NucleiTemplate>>;

export function GetScenarioGroups():Promise<Array<main.ScenarioGroup>>;

export function GetTargetByID(arg1:number):Promise<main.Target>;

export function GetTemplateEnabled(arg1:string):Promise<boolean>;

export function GetVulnerabilitiesByTaskID(arg1:number):Promise<Array<main.Vulnerability>>;

export function HealthCheck():Promise<Record<string, any>>;

export function ImportTemplate(arg1:string,arg2:string):Promise<string>;

export function InstallNuclei():Promise<void>;

export function LogFromFrontend(arg1:string,arg2:string):Promise<void>;

export function RemoveTemplatesFromScenarioGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function SearchNucleiTemplates(arg1:string):Promise<Array<main.NucleiTemplate>>;

export function SetCategoryEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetTemplateEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartScan(arg1:number):Promise<void>;

export function StopScan(arg1:number):Promise<void>;

export function ToggleCustomTemplate(arg1:number,arg2:boolean):Promise<void>;

export function UpdateCustomTemplate(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateHttpRequest(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>,arg6:string,arg7:string,arg8:Array<string>):Promise<void>;

export function UpdateScanTaskProgress(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function UpdateScanTaskStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateScenarioGroup(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function UpdateTarget(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateVulnerability(arg1:number,arg2:boolean,arg3:string):Promise<void>;

export function ValidateCustomTemplate(arg1:string):Promise<Record<string, any>>;

export function ValidateTemplate(arg1:string):Promise<Record<string, any>>;
