// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBrutePayloadSet(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function CreateBruteTask(arg1:string,arg2:number,arg3:string):Promise<number>;

export function CreateDomainBruteTask(arg1:string,arg2:Array<string>,arg3:number,arg4:number):Promise<number>;

export function CreateHttpRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:string,arg7:Array<string>):Promise<number>;

export function CreatePortScanTask(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<number>;

export function CreateScanTask(arg1:number,arg2:string,arg3:Array<string>):Promise<number>;

export function CreateTarget(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<number>;

export function CreateVulnerability(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number):Promise<number>;

export function DeleteHttpRequest(arg1:number):Promise<void>;

export function DeleteScanTask(arg1:number):Promise<void>;

export function DeleteTarget(arg1:number):Promise<void>;

export function DeleteVulnerability(arg1:number):Promise<void>;

export function GetAllBrutePayloadSets():Promise<Array<main.BrutePayloadSet>>;

export function GetAllBruteTasks():Promise<Array<main.BruteTask>>;

export function GetAllConfigs():Promise<Record<string, string>>;

export function GetAllDomainBruteTasks():Promise<Array<main.DomainBruteTask>>;

export function GetAllHttpRequests():Promise<Array<main.HttpRequest>>;

export function GetAllPortScanTasks():Promise<Array<main.PortScanTask>>;

export function GetAllScanTasks():Promise<Array<main.ScanTask>>;

export function GetAllTargets():Promise<Array<main.Target>>;

export function GetAllVulnerabilities():Promise<Array<main.Vulnerability>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDomainBruteResults(arg1:number):Promise<Array<main.DomainBruteResult>>;

export function GetHttpRequestByID(arg1:number):Promise<main.HttpRequest>;

export function GetHttpResponseHistory(arg1:number):Promise<Array<main.HttpResponse>>;

export function GetPortScanResults(arg1:number):Promise<Array<main.PortScanResult>>;

export function GetScanTaskByID(arg1:number):Promise<main.ScanTask>;

export function GetTargetByID(arg1:number):Promise<main.Target>;

export function GetVulnerabilitiesByTaskID(arg1:number):Promise<Array<main.Vulnerability>>;

export function HealthCheck():Promise<Record<string, any>>;

export function LogFromFrontend(arg1:string,arg2:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateHttpRequest(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>,arg6:string,arg7:string,arg8:Array<string>):Promise<void>;

export function UpdateScanTaskProgress(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function UpdateScanTaskStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTarget(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateVulnerability(arg1:number,arg2:boolean,arg3:string):Promise<void>;
