linters-settings:
  govet:
    disable:
      - shadow
      - fieldalignment
  gofmt:
    simplify: true

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: main.go
      linters:
        - typecheck
    - path: internal/app/
      linters:
        - typecheck
    - path: internal/svc/
      linters:
        - typecheck
    - path: internal/handler/
      linters:
        - typecheck

run:
  timeout: 5m
  tests: true
