// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateScanTask'](arg1, arg2, arg3, arg4);
}

export function CreateTarget(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTarget'](arg1, arg2, arg3, arg4);
}

export function DeleteScanTask(arg1) {
  return window['go']['app']['App']['DeleteScanTask'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['app']['App']['DeleteTarget'](arg1);
}

export function DeleteVulnerability(arg1) {
  return window['go']['app']['App']['DeleteVulnerability'](arg1);
}

export function GetAllScanTasks() {
  return window['go']['app']['App']['GetAllScanTasks']();
}

export function GetAllTargets() {
  return window['go']['app']['App']['GetAllTargets']();
}

export function GetAllTemplates() {
  return window['go']['app']['App']['GetAllTemplates']();
}

export function GetAllVulnerabilities() {
  return window['go']['app']['App']['GetAllVulnerabilities']();
}

export function GetDashboardStats() {
  return window['go']['app']['App']['GetDashboardStats']();
}

export function GetNucleiStatus() {
  return window['go']['app']['App']['GetNucleiStatus']();
}

export function GetScanTaskByID(arg1) {
  return window['go']['app']['App']['GetScanTaskByID'](arg1);
}

export function GetScanTasksByTargetID(arg1) {
  return window['go']['app']['App']['GetScanTasksByTargetID'](arg1);
}

export function GetTargetByID(arg1) {
  return window['go']['app']['App']['GetTargetByID'](arg1);
}

export function GetTemplateByID(arg1) {
  return window['go']['app']['App']['GetTemplateByID'](arg1);
}

export function GetTemplateCategories() {
  return window['go']['app']['App']['GetTemplateCategories']();
}

export function GetTemplateSeverities() {
  return window['go']['app']['App']['GetTemplateSeverities']();
}

export function GetTemplatesByCategory(arg1) {
  return window['go']['app']['App']['GetTemplatesByCategory'](arg1);
}

export function GetTemplatesBySeverity(arg1) {
  return window['go']['app']['App']['GetTemplatesBySeverity'](arg1);
}

export function GetVulnerabilitiesByTaskID(arg1) {
  return window['go']['app']['App']['GetVulnerabilitiesByTaskID'](arg1);
}

export function GetVulnerabilityByID(arg1) {
  return window['go']['app']['App']['GetVulnerabilityByID'](arg1);
}

export function LogFromFrontend(arg1, arg2) {
  return window['go']['app']['App']['LogFromFrontend'](arg1, arg2);
}

export function MarkVulnerabilityFalsePositive(arg1, arg2) {
  return window['go']['app']['App']['MarkVulnerabilityFalsePositive'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['app']['App']['StartScan'](arg1);
}

export function StopScan(arg1) {
  return window['go']['app']['App']['StopScan'](arg1);
}

export function UpdateTarget(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateTarget'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateVulnerabilityNotes(arg1, arg2) {
  return window['go']['app']['App']['UpdateVulnerabilityNotes'](arg1, arg2);
}
