// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateScanTask(arg1:string,arg2:number,arg3:string,arg4:Array<string>):Promise<models.ScanTask>;

export function CreateTarget(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Target>;

export function DeleteScanTask(arg1:number):Promise<void>;

export function DeleteTarget(arg1:number):Promise<void>;

export function DeleteVulnerability(arg1:number):Promise<void>;

export function GetAllScanTasks():Promise<Array<models.ScanTask>>;

export function GetAllTargets():Promise<Array<models.Target>>;

export function GetAllTemplates():Promise<Array<models.NucleiTemplate>>;

export function GetAllVulnerabilities():Promise<Array<models.Vulnerability>>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetNucleiStatus():Promise<models.NucleiStatus>;

export function GetScanTaskByID(arg1:number):Promise<models.ScanTask>;

export function GetScanTasksByTargetID(arg1:number):Promise<Array<models.ScanTask>>;

export function GetTargetByID(arg1:number):Promise<models.Target>;

export function GetTemplateByID(arg1:string):Promise<models.NucleiTemplate>;

export function GetTemplateCategories():Promise<Array<string>>;

export function GetTemplateSeverities():Promise<Array<string>>;

export function GetTemplatesByCategory(arg1:string):Promise<Array<models.NucleiTemplate>>;

export function GetTemplatesBySeverity(arg1:string):Promise<Array<models.NucleiTemplate>>;

export function GetVulnerabilitiesByTaskID(arg1:number):Promise<Array<models.Vulnerability>>;

export function GetVulnerabilityByID(arg1:number):Promise<models.Vulnerability>;

export function LogFromFrontend(arg1:string,arg2:string):Promise<void>;

export function MarkVulnerabilityFalsePositive(arg1:number,arg2:boolean):Promise<void>;

export function StartScan(arg1:number):Promise<void>;

export function StopScan(arg1:number):Promise<void>;

export function UpdateTarget(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateVulnerabilityNotes(arg1:number,arg2:string):Promise<void>;
