// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTemplatesToScenarioGroup(arg1, arg2) {
  return window['go']['app']['App']['AddTemplatesToScenarioGroup'](arg1, arg2);
}

export function CreateBrutePayloadSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateBrutePayloadSet'](arg1, arg2, arg3);
}

export function CreateBruteTask(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateBruteTask'](arg1, arg2, arg3);
}

export function CreateCustomTemplate(arg1) {
  return window['go']['app']['App']['CreateCustomTemplate'](arg1);
}

export function CreateDomainBruteTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateDomainBruteTask'](arg1, arg2, arg3, arg4);
}

export function CreateHttpRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateHttpRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePortScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreatePortScanTask'](arg1, arg2, arg3, arg4);
}

export function CreateReport(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateReport'](arg1, arg2, arg3, arg4);
}

export function CreateScanTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateScanTask'](arg1, arg2, arg3, arg4);
}

export function CreateScenarioGroup(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateScenarioGroup'](arg1, arg2, arg3, arg4);
}

export function CreateTarget(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTarget'](arg1, arg2, arg3, arg4);
}

export function DeleteBruteTask(arg1) {
  return window['go']['app']['App']['DeleteBruteTask'](arg1);
}

export function DeleteCustomTemplate(arg1) {
  return window['go']['app']['App']['DeleteCustomTemplate'](arg1);
}

export function DeleteHttpRequest(arg1) {
  return window['go']['app']['App']['DeleteHttpRequest'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['app']['App']['DeleteReport'](arg1);
}

export function DeleteScanTask(arg1) {
  return window['go']['app']['App']['DeleteScanTask'](arg1);
}

export function DeleteScenarioGroup(arg1) {
  return window['go']['app']['App']['DeleteScenarioGroup'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['app']['App']['DeleteTarget'](arg1);
}

export function DeleteVulnerability(arg1) {
  return window['go']['app']['App']['DeleteVulnerability'](arg1);
}

export function ExportReport(arg1, arg2) {
  return window['go']['app']['App']['ExportReport'](arg1, arg2);
}

export function GetAllBrutePayloadSets() {
  return window['go']['app']['App']['GetAllBrutePayloadSets']();
}

export function GetAllBruteTasks() {
  return window['go']['app']['App']['GetAllBruteTasks']();
}

export function GetAllCustomTemplates() {
  return window['go']['app']['App']['GetAllCustomTemplates']();
}

export function GetAllHttpRequests() {
  return window['go']['app']['App']['GetAllHttpRequests']();
}

export function GetAllReports() {
  return window['go']['app']['App']['GetAllReports']();
}

export function GetAllScanTasks() {
  return window['go']['app']['App']['GetAllScanTasks']();
}

export function GetAllScenarioGroups() {
  return window['go']['app']['App']['GetAllScenarioGroups']();
}

export function GetAllTargets() {
  return window['go']['app']['App']['GetAllTargets']();
}

export function GetAllTemplates() {
  return window['go']['app']['App']['GetAllTemplates']();
}

export function GetAllVulnerabilities() {
  return window['go']['app']['App']['GetAllVulnerabilities']();
}

export function GetBruteTaskResults(arg1) {
  return window['go']['app']['App']['GetBruteTaskResults'](arg1);
}

export function GetCustomTemplateByID(arg1) {
  return window['go']['app']['App']['GetCustomTemplateByID'](arg1);
}

export function GetCustomTemplatesStats() {
  return window['go']['app']['App']['GetCustomTemplatesStats']();
}

export function GetDashboardStats() {
  return window['go']['app']['App']['GetDashboardStats']();
}

export function GetDatabaseInfo() {
  return window['go']['app']['App']['GetDatabaseInfo']();
}

export function GetDomainBruteResults(arg1) {
  return window['go']['app']['App']['GetDomainBruteResults'](arg1);
}

export function GetHttpRequestByID(arg1) {
  return window['go']['app']['App']['GetHttpRequestByID'](arg1);
}

export function GetHttpResponseHistory(arg1) {
  return window['go']['app']['App']['GetHttpResponseHistory'](arg1);
}

export function GetNucleiStatus() {
  return window['go']['app']['App']['GetNucleiStatus']();
}

export function GetPortScanResults(arg1) {
  return window['go']['app']['App']['GetPortScanResults'](arg1);
}

export function GetReportById(arg1) {
  return window['go']['app']['App']['GetReportById'](arg1);
}

export function GetScanProgress(arg1) {
  return window['go']['app']['App']['GetScanProgress'](arg1);
}

export function GetScanTaskByID(arg1) {
  return window['go']['app']['App']['GetScanTaskByID'](arg1);
}

export function GetScanTasksByTargetID(arg1) {
  return window['go']['app']['App']['GetScanTasksByTargetID'](arg1);
}

export function GetScenarioGroupByID(arg1) {
  return window['go']['app']['App']['GetScenarioGroupByID'](arg1);
}

export function GetTargetByID(arg1) {
  return window['go']['app']['App']['GetTargetByID'](arg1);
}

export function GetTemplateAuthors() {
  return window['go']['app']['App']['GetTemplateAuthors']();
}

export function GetTemplateByID(arg1) {
  return window['go']['app']['App']['GetTemplateByID'](arg1);
}

export function GetTemplateCategories() {
  return window['go']['app']['App']['GetTemplateCategories']();
}

export function GetTemplateSeverities() {
  return window['go']['app']['App']['GetTemplateSeverities']();
}

export function GetTemplateStats() {
  return window['go']['app']['App']['GetTemplateStats']();
}

export function GetTemplatesPage(arg1, arg2) {
  return window['go']['app']['App']['GetTemplatesPage'](arg1, arg2);
}

export function GetTemplatesPageByFilter(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTemplatesPageByFilter'](arg1, arg2, arg3);
}

export function GetVulnerabilitiesByTaskID(arg1) {
  return window['go']['app']['App']['GetVulnerabilitiesByTaskID'](arg1);
}

export function GetVulnerabilitiesPage(arg1, arg2) {
  return window['go']['app']['App']['GetVulnerabilitiesPage'](arg1, arg2);
}

export function GetVulnerabilitiesPageByFilter(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetVulnerabilitiesPageByFilter'](arg1, arg2, arg3);
}

export function GetVulnerabilityByID(arg1) {
  return window['go']['app']['App']['GetVulnerabilityByID'](arg1);
}

export function HealthCheck() {
  return window['go']['app']['App']['HealthCheck']();
}

export function LogFromFrontend(arg1, arg2) {
  return window['go']['app']['App']['LogFromFrontend'](arg1, arg2);
}

export function MarkVulnerabilityFalsePositive(arg1, arg2) {
  return window['go']['app']['App']['MarkVulnerabilityFalsePositive'](arg1, arg2);
}

export function RemoveTemplatesFromScenarioGroup(arg1, arg2) {
  return window['go']['app']['App']['RemoveTemplatesFromScenarioGroup'](arg1, arg2);
}

export function SendHttpRequest(arg1, arg2) {
  return window['go']['app']['App']['SendHttpRequest'](arg1, arg2);
}

export function StartBruteTask(arg1) {
  return window['go']['app']['App']['StartBruteTask'](arg1);
}

export function StartScan(arg1) {
  return window['go']['app']['App']['StartScan'](arg1);
}

export function StopScan(arg1) {
  return window['go']['app']['App']['StopScan'](arg1);
}

export function ToggleCustomTemplate(arg1, arg2) {
  return window['go']['app']['App']['ToggleCustomTemplate'](arg1, arg2);
}

export function UpdateCustomTemplate(arg1, arg2) {
  return window['go']['app']['App']['UpdateCustomTemplate'](arg1, arg2);
}

export function UpdateHttpRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['UpdateHttpRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateScanTaskStatus(arg1, arg2) {
  return window['go']['app']['App']['UpdateScanTaskStatus'](arg1, arg2);
}

export function UpdateScenarioGroup(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateScenarioGroup'](arg1, arg2, arg3, arg4);
}

export function UpdateTarget(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateTarget'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateVulnerability(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateVulnerability'](arg1, arg2, arg3);
}

export function UpdateVulnerabilityNotes(arg1, arg2) {
  return window['go']['app']['App']['UpdateVulnerabilityNotes'](arg1, arg2);
}

export function ValidateCustomTemplate(arg1) {
  return window['go']['app']['App']['ValidateCustomTemplate'](arg1);
}
