// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTemplatesToScenarioGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateBrutePayloadSet(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function CreateBruteTask(arg1:string,arg2:number,arg3:string):Promise<number>;

export function CreateCustomTemplate(arg1:models.CreateTemplateRequest):Promise<models.Template>;

export function CreateDomainBruteTask(arg1:string,arg2:Array<string>,arg3:number,arg4:number):Promise<number>;

export function CreateHttpRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:string,arg7:Array<string>):Promise<models.HttpRequest>;

export function CreatePortScanTask(arg1:string,arg2:Array<number>,arg3:number,arg4:number):Promise<number>;

export function CreateReport(arg1:string,arg2:number,arg3:string,arg4:string):Promise<number>;

export function CreateScanTask(arg1:string,arg2:number,arg3:string,arg4:Array<string>):Promise<models.ScanTask>;

export function CreateScenarioGroup(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.ScenarioGroup>;

export function CreateTarget(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Target>;

export function DeleteBruteTask(arg1:number):Promise<void>;

export function DeleteCustomTemplate(arg1:number):Promise<void>;

export function DeleteHttpRequest(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function DeleteScanTask(arg1:number):Promise<void>;

export function DeleteScenarioGroup(arg1:string):Promise<void>;

export function DeleteTarget(arg1:number):Promise<void>;

export function DeleteVulnerability(arg1:number):Promise<void>;

export function ExportReport(arg1:number,arg2:string):Promise<string>;

export function GetAllBrutePayloadSets():Promise<Array<models.BrutePayloadSet>>;

export function GetAllBruteTasks():Promise<Array<models.BruteTask>>;

export function GetAllCustomTemplates():Promise<Array<models.Template>>;

export function GetAllHttpRequests():Promise<Array<models.HttpRequest>>;

export function GetAllReports():Promise<Array<models.Report>>;

export function GetAllScanTasks():Promise<Array<models.ScanTask>>;

export function GetAllScenarioGroups():Promise<Array<models.ScenarioGroup>>;

export function GetAllTargets():Promise<Array<models.Target>>;

export function GetAllTemplates():Promise<Array<models.Template>>;

export function GetAllVulnerabilities():Promise<Array<models.Vulnerability>>;

export function GetBruteTaskResults(arg1:number):Promise<Array<models.BruteResult>>;

export function GetCustomTemplateByID(arg1:number):Promise<models.Template>;

export function GetCustomTemplatesStats():Promise<Record<string, any>>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDomainBruteResults(arg1:number):Promise<Array<models.DomainBruteResult>>;

export function GetHttpRequestByID(arg1:number):Promise<models.HttpRequest>;

export function GetHttpResponseHistory(arg1:number):Promise<Array<models.HttpResponse>>;

export function GetNucleiStatus():Promise<models.NucleiStatus>;

export function GetPortScanResults(arg1:number):Promise<Array<models.PortScanResult>>;

export function GetReportById(arg1:number):Promise<models.Report>;

export function GetScanProgress(arg1:number):Promise<models.ScanProgress>;

export function GetScanTaskByID(arg1:number):Promise<models.ScanTask>;

export function GetScanTasksByTargetID(arg1:number):Promise<Array<models.ScanTask>>;

export function GetScenarioGroupByID(arg1:string):Promise<models.ScenarioGroup>;

export function GetTargetByID(arg1:number):Promise<models.Target>;

export function GetTemplateAuthors():Promise<Array<string>>;

export function GetTemplateByID(arg1:number):Promise<models.Template>;

export function GetTemplateCategories():Promise<Array<string>>;

export function GetTemplateSeverities():Promise<Array<string>>;

export function GetTemplateStats():Promise<Record<string, number>>;

export function GetTemplatesPage(arg1:number,arg2:number):Promise<Array<models.Template>>;

export function GetTemplatesPageByFilter(arg1:models.TemplateFilterUnified,arg2:number,arg3:number):Promise<Array<models.Template>>;

export function GetVulnerabilitiesByTaskID(arg1:number):Promise<Array<models.Vulnerability>>;

export function GetVulnerabilitiesPage(arg1:number,arg2:number):Promise<Array<models.Vulnerability>>;

export function GetVulnerabilitiesPageByFilter(arg1:models.VulnerabilityFilter,arg2:number,arg3:number):Promise<Array<models.Vulnerability>>;

export function GetVulnerabilityByID(arg1:number):Promise<models.Vulnerability>;

export function HealthCheck():Promise<void>;

export function LogFromFrontend(arg1:string,arg2:string):Promise<void>;

export function MarkVulnerabilityFalsePositive(arg1:number,arg2:boolean):Promise<void>;

export function RemoveTemplatesFromScenarioGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function SendHttpRequest(arg1:number,arg2:number):Promise<models.HttpResponse>;

export function StartBruteTask(arg1:number):Promise<void>;

export function StartScan(arg1:number):Promise<void>;

export function StopScan(arg1:number):Promise<void>;

export function ToggleCustomTemplate(arg1:number,arg2:boolean):Promise<void>;

export function UpdateCustomTemplate(arg1:number,arg2:models.UpdateTemplateRequest):Promise<void>;

export function UpdateHttpRequest(arg1:number,arg2:any,arg3:any,arg4:any,arg5:Record<string, string>,arg6:any,arg7:any,arg8:Array<string>):Promise<void>;

export function UpdateScanTaskStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateScenarioGroup(arg1:string,arg2:any,arg3:any,arg4:Array<string>):Promise<void>;

export function UpdateTarget(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateVulnerability(arg1:number,arg2:boolean,arg3:string):Promise<void>;

export function UpdateVulnerabilityNotes(arg1:number,arg2:string):Promise<void>;

export function ValidateCustomTemplate(arg1:string):Promise<boolean>;
